import type { Metadata } from "next";
import "@/utils/admin.css";
import AdminTopBar from "./_components/AdminTopBar";
import AdminSideBar from "./_components/AdminSideBar";

export const metadata: Metadata = {
  title: "Graphics Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="admin-layout">
      <div className="admin-sidebar">
        <AdminSideBar />
      </div>
      <div className="admin-content">
        <AdminTopBar />
        <main className="admin-main">
          <div className="admin-children">
            {children}
          </div>
        </main>

      </div>
    </section>
  );
}
