import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/utils/admin.css";
import AdminTopBar from "@/components/AdminTopBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Graphics Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="admin-layout">
          <div className="admin-sidebar">

          </div>
          <div className="admin-content">
            <AdminTopBar />
            <main>
              {children}
            </main>

          </div>
        </section>
      </body>
    </html>
  );
}
