import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/utils/dashboard.css";
import ClientTopBar from "@/components/ClientTopBar";
import ClientSideBar from "@/components/ClientSideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Graphics Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="client-layout">
          <ClientSideBar />
          <div className="client-content">
            <ClientTopBar />
            <main className="main-content">
              {children}
            </main>

          </div>
        </section>
      </body>
    </html>
  );
}
