import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/utils/dashboard.css";
import ClientTopBar from "@/app/dashboard/_components/ClientTopBar";
import ClientSideBar from "@/app/dashboard/_components/ClientSideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Graphics Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="client-layout">
      <ClientSideBar />
      <div className="client-content">
        <ClientTopBar />
        <main className="main-content">
          {children}
        </main>
      </div>
    </section>
  );
}
